#!/bin/bash
set -e

psql -v ON_ERROR_STOP=0 --username $POSTGRES_USER --dbname $POSTGRES_DB <<-EOSQL
    CREATE USER $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD' LOGIN;
    CREATE DATABASE $POSTGRES_DB;
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER;

    CREATE USER postgres WITH PASSWORD '$POSTGRES_PASSWORD' LOGIN;
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO postgres;
EOSQL