version: "3.9"

services:

  flower:
    build:
      context: .
      dockerfile: docker/celery-flower/Dockerfile
    environment:
      - DATABASE_NAME=${DJANGO_POSTGRES_DB}
      - DATABASE_USER=${DJANGO_POSTGRES_USER}
      - DATABASE_PASSWORD=${DJANGO_DATABASE_PASSWORD}
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
      - celery-worker
    networks:
      - postgres
      - redis
      - celery-worker
    ports:
      - "5555:5555"
    env_file:
      - .env

  celery-worker:
    restart: always
    build:
      context: .
      dockerfile: docker/celery-worker/Dockerfile
    volumes:
      - ./django:/usr/src/app/django
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_NAME=${DJANGO_POSTGRES_DB}
      - DATABASE_USER=${DJANGO_POSTGRES_USER}
      - DATABASE_PASSWORD=${DJANGO_DATABASE_PASSWORD}
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - REDIS_URL=redis://redis:6379/0
    networks:
      - postgres
      - redis
      - celery-worker
    env_file:
      - .env

  celery-whisper-worker:
    restart: always
    build:
      context: .
      dockerfile: docker/celery-whisper-worker/Dockerfile
    volumes:
      - ./django:/usr/src/app/django
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_NAME=${DJANGO_POSTGRES_DB}
      - DATABASE_USER=${DJANGO_POSTGRES_USER}
      - DATABASE_PASSWORD=${DJANGO_DATABASE_PASSWORD}
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - REDIS_URL=redis://redis:6379/0
    networks:
      - postgres
      - redis
      - celery-worker
    env_file:
      - .env

  redis:
    image: "redis:alpine"
    networks:
      - redis

      
  django:
    restart: always
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./django:/usr/src/app/django
    environment:
      - DJANGO_DATABASE_HOST=postgres
      - DJANGO_DATABASE_PORT=5432
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    networks:
      - postgres
      - redis
    ports:
      - "8888:8888"

  postgres:
    container_name: postgres
    build: 
      context: ./docker/postgres
      # dockerfile: 
    environment:
      POSTGRES_USER: ${DJANGO_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DJANGO_DATABASE_PASSWORD}
      POSTGRES_DB: ${DJANGO_POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
      - ./.data/postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
    env_file:
      - .env

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - ./.data/pgadmin:/var/lib/pgadmin
    networks:
      - postgres
    depends_on:
      - postgres

    restart: unless-stopped
    env_file:
      - .env


    

networks:
  postgres:
    driver: bridge
  redis:
    driver: bridge
  celery-worker:
    driver: bridge

volumes:
  postgres: