version: "3.9"

services:

  flower:
    extends: 
      file: docker-compose.yml
      service: flower

  celery-worker:
    extends:
      file: docker-compose.yml
      service: celery-worker

  celery-whisper-worker:
    extends:
      file: docker-compose.yml
      service: celery-whisper-worker

  redis:
    extends:
      file: docker-compose.yml
      service: redis

  django:
    extends:
      file: docker-compose.yml
      service: django
    volumes:
      - ./django:/usr/src/app/django
    networks:
      - django
  
  postgres:
    extends:
      file: docker-compose.yml
      service: postgres

  pgadmin:
    extends:
      file: docker-compose.yml
      service: pgadmin
  
  frontend:
    restart: always
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    depends_on:
      - django
    env_file: 
      - .env.development
    ports:
      - "3000:3000"
    networks:
      - django
    volumes:
      - ./django:/usr/src/app/django
    

networks:
  postgres:
    driver: bridge
  redis:
    driver: bridge
  celery-worker:
    driver: bridge
  django:
    driver: bridge

volumes:
  postgres:

