version: '3'
services:
  redis:
    image: redis:latest
    expose:
      - 6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always
  scrapyd:
    platform: "linux/amd64"
    build: ./docker/scrapyd
    ports:
      - 6800:6800
    volumes:
      - ./scrapyd:/etc/scrapyd
    networks:
      - scrapy-network

  scrapyd-web:
    platform: "linux/amd64"
    build: ./docker/scrapyd-web 
    ports:
      - 5000:5000
    networks:
      - scrapy-network
    command: scrapydweb --scrapyd_server scrapyd:6800

networks:
  scrapy-network:
    driver: bridge