version: "3.9"

services:
  django:
    restart: always
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    depends_on:
      - django_postgres
    volumes:
      - .:/usr/src/app
    env_file:
      - ../.env
    networks:
      - django_postgres_network
    ports:
      - "8888:8888"

  django_postgres:
    container_name: django_postgres
    build: docker/postgres
    environment:
      POSTGRES_USER: ${DJANGO_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DJANGO_DATABASE_PASSWORD}
      POSTGRES_DB: ${DJANGO_POSTGRES_DB}
      # PGDATA: /data/postgres
    volumes:
      - ./data/postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - django_postgres_network
    restart: unless-stopped
    env_file:
      - ../.env

networks:
  django_postgres_network:
    name: django_postgres_network
    driver: bridge

volumes:
  django_postgres: