# Generated by Django 4.1.3 on 2022-12-01 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=2048, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('audio_url', models.CharField(max_length=2048)),
                ('details_url', models.CharField(max_length=2048)),
                ('transcription', models.TextField(blank=True, default=None, null=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.podcast')),
            ],
        ),
        migrations.AddConstraint(
            model_name='podcast',
            constraint=models.UniqueConstraint(fields=('url',), name='unique_podcast_url'),
        ),
    ]
