# Generated by Django 4.1.3 on 2022-12-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastepisode',
            name='details_url',
            field=models.CharField(max_length=2048, unique=True),
        ),
        migrations.AddConstraint(
            model_name='podcastepisode',
            constraint=models.UniqueConstraint(fields=('details_url',), name='unique_podcast_episode_details_url'),
        ),
    ]
