# Generated by Django 4.1.3 on 2022-11-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastepisode',
            name='audio_file_path',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
