# Generated by Django 4.1.3 on 2022-12-07 08:33

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_search_vector_trigger'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='podcastepisode',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='api_podcast_search__18e659_gin'),
        ),
    ]
