# Generated by Django 4.1.3 on 2022-12-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_podcast_active_podcast_description_podcast_logo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
