# Generated by Django 4.1.3 on 2022-12-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_podcastepisode_slug'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='podcast',
            index=models.Index(fields=['slug'], name='api_podcast_slug_b7d4a0_idx'),
        ),
        migrations.AddIndex(
            model_name='podcastepisode',
            index=models.Index(fields=['slug'], name='api_podcast_slug_205c8e_idx'),
        ),
    ]
