# Generated by Django 4.1.3 on 2022-12-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_podcast_api_podcast_slug_b7d4a0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastepisode',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
