# Generated by Django 4.1.3 on 2022-12-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_podcastepisode_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcastepisode',
            name='transcription',
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='grouped_transcription',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='whisper_transcription_object',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
