# Generated by Django 4.1.3 on 2022-12-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_grouped_transcription_podcastepisode_transcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='is_rss',
            field=models.BooleanField(default=True),
        ),
    ]
