# Generated by Django 4.1.3 on 2022-12-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_podcast_is_rss'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastepisode',
            name='whisper_model_size',
            field=models.CharField(choices=[('tiny', 'tiny'), ('base', 'base'), ('small', 'small'), ('medium', 'medium'), ('large', 'large')], default='base', max_length=10),
        ),
    ]
